# Generated by Django 6.0.1 on 2026-01-30 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_conversation_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='AI-generated conversation summary'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='summary_token_count',
            field=models.IntegerField(default=0, help_text='Token count at time of summary generation', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='message',
            name='model_used',
            field=models.CharField(blank=True, default='', help_text='Model used for this message (may differ from conversation default)', max_length=50),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-created_at'], name='msg_created_desc_idx'),
        ),
    ]
