# Generated by Django 6.0.1 on 2026-03-24 07:54

import django.core.validators
import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditBalance',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'credit balance',
                'verbose_name_plural': 'credit balances',
                'db_table': 'credit_balances',
            },
        ),
        migrations.CreateModel(
            name='CreditPackage',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('credits', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField(help_text='Price in TWD (integer)')),
                ('description', models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(500)])),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'credit package',
                'verbose_name_plural': 'credit packages',
                'db_table': 'credit_packages',
                'ordering': ['sort_order', 'price'],
                'indexes': [models.Index(fields=['is_active', 'sort_order'], name='pkg_active_sort_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('merchant_trade_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('amount', models.PositiveIntegerField(help_text='TWD amount snapshot at order creation')),
                ('credits_awarded', models.PositiveIntegerField(help_text='Credits snapshot at order creation')),
                ('ecpay_trade_no', models.CharField(blank=True, default='', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('rtn_code', models.CharField(blank=True, default='', max_length=10)),
                ('rtn_msg', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payments.creditpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment order',
                'verbose_name_plural': 'payment orders',
                'db_table': 'payment_orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='order_user_created_idx'), models.Index(fields=['status'], name='order_status_idx')],
            },
        ),
    ]
